# Generated by Django 4.2.3 on 2023-09-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(default='NULL', upload_to='photo/'),
        ),
    ]
